### ISSUE TITLE
train.yaml in the tutorial is invalid

### ISSUE THREAD

**Issue by raimis** [torchmd/torchmd-cg#11]
```bash
$ cat train.yaml 
lr: 0.0001
batch_size: 1024
num_epochs: 200
coords: "data/chignolin_ca_coords.npy"
forces: "data/chignolin_ca_deltaforces.npy"
embeddings: "data/chignolin_ca_embeddings.npy"
log_dir: train_light
label: forces
derivative: forces
gpus: 4
distributed_backend: dp
num_nodes: 1
eval_interval: 1
test_interval: 1
save_interval: 1
seed: 1
progress: True
val_ratio: 0.05
test_ratio: 0.1
num_workers: 8
num_filters: 128
num_gaussians: 150
num_interactions: 3
max_z: 100
cutoff: 9
lr_patience: 4
lr_min: 1.e-06
lr_factor: 0.8
$ python ../scripts/light_train.py -c train.yaml
Number of trainable parameters 276865
/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: Checkpoint directory train_light exists and is not empty with save_top_k=8 All files in this directory will be deleted when a checkpoint is saved!
  warnings.warn(*args, **kwargs)
Traceback (most recent call last):
  File "../scripts/light_train.py", line 283, in <module>
    main()
  File "../scripts/light_train.py", line 262, in main
    test_percent_check=percent,
TypeError: __init__() got an unexpected keyword argument 'train_percent_check'
```

**Comment by giadefa** [comment]
try now

**Comment by raimis** [comment]
Fails with another error:
```python
$ python ../scripts/light_train.py -c train.yaml
Number of trainable parameters 276865
/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: Checkpoint directory train_light exists and is not empty with save_top_k=8 All files in this directory will be deleted when a checkpoint is saved!
  warnings.warn(*args, **kwargs)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
Preparing data...
Coordinates files:  1
Forces files:  1
Embeddings files:  1
Combined dataset size 18689
train 15885, val 934, test 1870

  | Name    | Type           | Params
-------------------------------------------
0 | model   | AtomisticModel | 276 K 
1 | loss_fn | MSELoss        | 0     
2 | test_fn | L1Loss         | 0     
Warning: Dataset lenght 934. Reducing batch_size 33
Validation sanity check:  50%|██████████████████████████████████████████████████████▌                                                      | 1/2 [00:07<00:07,  7.62s/it]/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: The validation_epoch_end should not return anything as of 9.1.to log, use self.log(...) or self.write(...) directly in the LightningModule
  warnings.warn(*args, **kwargs)
/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/pytorch_lightning/utilities/distributed.py:45: UserWarning: The {log:dict keyword} was deprecated in 0.9.1 and will be removed in 1.0.0
Please use self.log(...) inside the lightningModule instead.

# log on a step or aggregate epoch metric to the logger and/or progress bar
# (inside LightningModule)
self.log('train_loss', loss, on_step=True, on_epoch=True, prog_bar=True)
  warnings.warn(*args, **kwargs)
Warning: Dataset lenght 15885. Reducing batch_size 500
Epoch 0:   0%|                                                                                                                                    | 0/61 [00:00<?, ?it/s]/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/torch/nn/parallel/_functions.py:61: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Epoch 0: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 61/61 [00:07<00:00,  8.48it/s, loss=753.402, v_num=2Traceback (most recent call last):                                                                                                                                        
  File "/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/optimizer_connector.py", line 47, in update_learning_rates
    monitor_key = lr_scheduler['monitor']
KeyError: 'monitor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../scripts/light_train.py", line 280, in <module>
    main()
  File "../scripts/light_train.py", line 262, in main
    trainer.fit(model)
  File "/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 454, in fit
    results = self.accelerator_backend.train()
  File "/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/pytorch_lightning/accelerators/dp_backend.py", line 96, in train
    results = self.train_or_test()
  File "/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/pytorch_lightning/accelerators/base_accelerator.py", line 50, in train_or_test
    results = self.trainer.train()
  File "/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in train
    self.optimizer_connector.update_learning_rates(interval='epoch')
  File "/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/optimizer_connector.py", line 52, in update_learning_rates
    raise MisconfigurationException(m)
pytorch_lightning.utilities.exceptions.MisconfigurationException: ReduceLROnPlateau requires returning a dict from configure_optimizers with the keyword monitor=. For example:return {'optimizer': optimizer, 'lr_scheduler': scheduler, 'monitor': 'your_loss'}
Exception ignored in: <function tqdm.__del__ at 0x7fb65a9327a0>
Traceback (most recent call last):
  File "/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/tqdm/std.py", line 1122, in __del__
  File "/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/tqdm/std.py", line 1335, in close
  File "/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/tqdm/std.py", line 1514, in display
  File "/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/tqdm/std.py", line 1125, in __repr__
  File "/shared/raimis/opt/miniconda/envs/torchmd_cg/lib/python3.7/site-packages/tqdm/std.py", line 1475, in format_dict
TypeError: cannot unpack non-iterable NoneType object

```

**Comment by giadefa** [comment]
@raimis everything should be working now

**Comment by ARKAtheVLOGGER** [comment]
coords: "data/chignolin_ca_coords.npy"
forces: "data/chignolin_ca_deltaforces.npy 
How you guys create this .npy file. I have run my simulation on an amber forcefield. I have initial .coor file. is that chignolin_ca_coords.npy file or something different? and what about chignolin_ca_forces.npy file?
